# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: rpc/ThingService.proto for package 'rpc'

require 'grpc'
require 'rpc/ThingService_pb'

module Rpc
  module ThingService
    # Demonstration service
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'rpc.ThingService'

      # Request calls
      # For testing a request/response call
      rpc :GetThing, GetThingRequest, GetThingResponse
      # For testing a server streaming call
      rpc :GetThings, GetThingsRequest, stream(Thing)
      # For testing a client streaming call
      rpc :CreateThings, stream(Thing), CreateThingsResponse
      # For testing a bidirectional streaming call
      rpc :CreateThingsInStream, stream(Thing), stream(Thing)
      # Error calls
      # For testing a generic failure
      rpc :GetFail, GetThingRequest, GetThingResponse
      # For testing a field error
      rpc :GetFieldErrorFail, GetThingRequest, GetThingResponse
      # For testing an exception
      rpc :GetException, GetThingRequest, GetThingResponse
      # For testing an uncaught exception
      rpc :GetUncaughtException, GetThingRequest, GetThingResponse
    end

    Stub = Service.rpc_stub_class
  end
end
