# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/test/Service2.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("rpc/test/Service2.proto", :syntax => :proto3) do
    add_message "rpc.test.Product2" do
      optional :id, :uint32, 1
      optional :name, :string, 2
    end
    add_message "rpc.test.Get2Request" do
      optional :id, :uint32, 1
    end
  end
end

module Rpc
  module Test
    Product2 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.test.Product2").msgclass
    Get2Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.test.Get2Request").msgclass
  end
end
