# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/test/Service2.proto

require 'google/protobuf'


descriptor_data = "\n\x17rpc/test/Service2.proto\x12\x08rpc.test\"$\n\x08Product2\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x19\n\x0bGet2Request\x12\n\n\x02id\x18\x01 \x01(\r2?\n\x08Service2\x12\x33\n\x04Get2\x12\x15.rpc.test.Get2Request\x1a\x12.rpc.test.Product2\"\x00\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Rpc
  module Test
    Product2 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.test.Product2").msgclass
    Get2Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.test.Get2Request").msgclass
  end
end
