# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/test/Service3.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("rpc/test/Service3.proto", :syntax => :proto3) do
    add_message "rpc.test.Product3" do
      optional :id, :uint32, 1
      optional :name, :string, 2
    end
    add_message "rpc.test.Get3Request" do
      optional :id, :uint32, 1
    end
  end
end

module Rpc
  module Test
    Product3 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.test.Product3").msgclass
    Get3Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.test.Get3Request").msgclass
  end
end
